### ISSUE TITLE
@conda-forge-admin please add user @j-rivero

### ISSUE THREAD

**Issue by j-rivero** [conda-forge/colcon-core-feedstock#54]
Agreed with @traversaro to help in the maintenance from the Infra team at Open Source Robotics Alliance (OSRA)

**Comment by traversaro** [comment]
> Agreed with [@traversaro](https://github.com/traversaro) to help in the maintenance from the Infra team at Open Source Robotics Alliance (OSRA)

Thanks!

fyi @wolfv @Tobias-Fischer
